### ISSUE TITLE
Features Roadmap

### ISSUE THREAD

**Issue by pustovitDmytro** [pustovitDmytro/tastoria#3]
- [x] share receipt
- [x] print receipt
- [x] add shared to mine recipes
- [ ] social network (friends, likes, comments, blog, chat)
- [ ] bulk recipes editor
- [x] edit single recipe
- [ ] shopping list
- [ ] meal planner
- [x]  login by email
- [x] create recipy
- [ ] archived library
- [ ]  import from url
